# Generated by Django 2.2.4 on 2019-09-18 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='user_id',
            new_name='owner',
        ),
    ]
